Added full-upgrade, autoremove, search and show commands Removed uninstall in favor of apt's native remove command

diff --git a/nixapt b/nixapt
--- a/nixapt
+++ b/nixapt
@@ -3,10 +3,8 @@
 switch $argv[1]
 	case update
 		nix-channel --update nixpkgs
-	case upgrade
+	case upgrade full-upgrade
 		nix-env --upgrade '*'
-	case list
-		nix-env --query $argv[2..-1]
 	case install
 		if test -z $argv[2]
 			echo "Package(s) name required"
@@ -14,13 +12,28 @@ switch $argv[1]
 		else
 			nix-env --install --attr nixpkgs.{$argv[2..-1]}
 		end
-	case uninstall
+	case remove
 		if test -z $argv[2]
 			echo "Package(s) name required"
 			exit 1
 		else
 			nix-env --uninstall $argv[2..-1]
 		end
+	case autoremove
+		nix-collect-garbage -d
+	case search show
+		if test -z $argv[2]
+			echo "Package(s) name required"
+			exit 1
+		else
+			if command -q jq
+				nix-env -qa --json $argv[2..-1] | jq
+			else
+				nix-env -qa --json $argv[2..-1]
+			end
+		end
+	case list
+		nix-env --query $argv[2..-1]
 	case '' '--help' '-h'
 		echo "OVERVIEW: Simple wrapper for apt-style commands with Nix on macOS"
 		echo
